### ISSUE TITLE
User models

### ISSUE THREAD

**Issue by yafithekid** [yafithekid/ecash-toll-api#5]
user menyimpan:
id
msisdn (phone number)
credentials (token)
token

**Comment by ichwanhs96** [comment]
goddamit

**Comment by ichwanhs96** [comment]
credential -> varchar (64)
token -> varchar (255)

**Comment by yafithekid** [comment]
gak masalah itu varchar 255 jg ok.

credentials bukan credential

**Comment by ichwanhs96** [comment]
got it
